t ?= esp8266

TERMINAL_SPEED := 115200
TERMINAL_EXTRA_FLAGS := -C serialout.txt
CPPFLAGS = -Wall -DDEBUGGING=0x33 -DCPU_DEBUG=1 -DTERMINAL_SPEED=$(TERMINAL_SPEED) -DSIMPLE_TIMER_MICROS
LIBRARIES = PS2KeyAdvanced PS2KeyMap SimpleTimer Adafruit_GFX Adafruit_BusIO Wire SPI

ifeq ($t, esp8266)
BOARD := d1_mini
baud := 921600
eesz := 4M1M
CPPFLAGS += -DUSER_SETUP_LOADED -DILI9341_DRIVER -DTFT_CS=PIN_D8 -DTFT_DC=PIN_D1 \
	-DTFT_RST=-1 -DSPI_FREQUENCY=40000000 -DLOAD_GLCD \
	-DHARDWARE_H=\"hw/esp8bit.h\" -DPS2_SERIAL_KBD=\"UK\"
LIBRARIES += TFT_eSPI SpiRAM LittleFS
endif

-include $t.mk
